apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "external-app.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.app.storageclassname }}
  resources:
    requests:
      storage: {{ .Values.storage.app.storagesize }}
