affinity: {}
cm: node-internal-app
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: intainregistry/saludagrade2-internal-app-production:1.0.2
imagePullSecrets:
- name: regcred
ingress:
  annotations: {}
  enabled: false
  hosts:
  - host: chart-example.local
    paths: []
  tls: []
metadata:
  name: node-internal-app
  namespace: fabricclient
name: cm-data
nameOverride: ""
nodeSelector: {}
podSecurityContext: {}
replicaCount: 1
securityContext: {}
service:
  port: 4000
  type: ClusterIP
serviceAccount:
  create: true
  name: null
storage:
  app:
    storageclassname: fabricclient-disksc
    storagesize: 1Gi
tolerations: []
